class ConversationError(ValueError): ...

MAX_EVENT_BYTES: int
WIRE_VERSION: int

class ConversationModel:
    def __init__(self, conversation_id: str) -> None: ...
    @property
    def id(self) -> str: ...
    def apply_json(self, event_json: str) -> bool: ...
    def snapshot_json(self) -> str: ...
